vim.loader.enable()

require("config.globals")
require("config.lazy")
require("config.colorscheme")
require("config.keymap")
require("config.telescope")
require("config.toggleterm")
require("config.indent_blankline")
require("config.ufo")
require("config.oil")
require("config.flash")
require("config.which_key")
require("config.todo_comments")
require("config.trouble")
require("config.notify")
require("config.nvim_autopairs")
require("config.lualine")
